languageCode = "en-us"
title = "sbt-plugin-tour"
theme = "purehugo"

[params]
  twitterName = "indyscala"
  githubName = "indyscala"
  description = "Bringing you Hello World - one character at a time"
  hideShareOptions = true
